# Azure is great for testing our projects before we merge them into the main code.
# It's a good idea to have all checks acheived before merging.
# And if not acheived, you can see where you went wrong.

# I added a few more test cases. I don't expect all of them to be there during build season
# just testing what works and what doesn't.

resources:
  containers:
  - container: linux_jaci #Jaci's Linux, from (https://github.com/JacisNonsense/azure-native-linux)
    image: jaci/azure-native-linux:2018.12.06
  - container: wpilib2019
    image: wpilib/roborio-cross-ubuntu:2019-18.04
  - container: raspbian
    image:  wpilib/raspbian-cross-ubuntu:18.04

jobs:

- job: windows_teamcode_Build
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
  - template: azure-init.yml
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: ':4788:build'
      options: '-Pno-roborio'

- job: linuxLatest_teamcode_Build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      tasks: ':4788:build'

- job: macOS_teamcode_Build
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - template: azure-init.yml
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: ':4788:build'
      options: '-Pno-roborio'

- job: windows_full_build
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
  - template: azure-init.yml
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean build'
      options: '-Pno-roborio'

- job: linuxLatest_full_build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean build'

- job: macOS_full_build
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - template: azure-init.yml
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean build'
      options: '-Pno-roborio'

- job: linux16_full_build
  pool: 
    vmImage: 'Ubuntu-16.04'
  container: linux
  steps:
  - script: sudo apt-get install -y libusb-1.0-0-dev
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean build'
      options: '-Pno-roborio'

- job: roborio_linux16_full_build
  pool: 
    vmImage: 'Ubuntu-16.04'
  container: wpilib2019
  steps:
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean build'
      options: '-Pno-desktop -xcheck -x:vision:build'

- job: pi_vision_linux16
  pool: 
    vmImage: 'Ubuntu-16.04'
  container: raspbian
  steps:
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean :vision:build'
      options: '-Pno-roborio -Pno-desktop -xcheck'

- job: tinkerboard_vision_linux16
  pool:
    vmImage: 'Ubuntu-16.04'
  container: linux
  steps:
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      tasks: ':vision:installTinkerboardToolchain'
      options: '-Pno-roborio -Pno-desktop --scan --stacktrace'
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean :vision:build'
      options: '-Pno-roborio -Pno-desktop -xcheck'

- job: tinkerboard_vision_linuxLatest
  pool:
    vmImage: 'ubuntu-lastest'
  container: linux
  steps:
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      tasks: ':vision:installTinkerboardToolchain'
      options: '-Pno-roborio -Pno-desktop --scan --stacktrace'
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean :vision:build'
      options: '-Pno-roborio -Pno-desktop -xcheck'

- job: doxygen
  pool:
    vmImage: 'Ubuntu-16.04'
  container: linux
  steps:
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      tasks: 'doxygen'
      options: '-Pno-roborio'
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'doxygen'
      pathtoPublish: build/docs/doxygen/html
